# Generated by Django 4.2.1 on 2024-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='protocols',
            field=models.JSONField(default=['uci']),
        ),
        migrations.AddField(
            model_name='test',
            name='base_protocol',
            field=models.CharField(default='uci', max_length=32),
        ),
        migrations.AddField(
            model_name='test',
            name='dev_protocol',
            field=models.CharField(default='uci', max_length=32),
        ),
    ]
