# Generated by Django 4.2.1 on 2024-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0002_engine_protocols_test_base_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='protocols',
            field=models.JSONField(default=list),
        ),
    ]
