# Generated by Django 4.2.1 on 2024-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0003_alter_engine_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scale_method',
            field=models.CharField(choices=[('DEV', 'DEV'), ('BASE', 'BASE'), ('BOTH', 'BOTH')], default='BASE', max_length=16),
        ),
        migrations.AddField(
            model_name='test',
            name='scale_nps',
            field=models.IntegerField(default=0),
        ),
    ]
